### PR TITLE
feat: Fix live data chart and display weather from server

### LINKED ISSUE #18: feat: Fix live data chart and display weather from server

### PR DESCRIPTION
**Pull request by marimarimarietty**

### CODE REVIEW

File: src/components/molecules/Weather.tsx [hunk 1]
```diff
@@ -27,18 +21,18 @@ export default function Weather(props: Props) {
...
-      "February",
-      "March",
-      "April",
+      "Jan.",
+      "Feb.",
+      "Mar.",
+      "Apr.",
       "May",
       "June",
       "July",
```
Comment (Takashicc) [inline src/components/molecules/Weather.tsx]: How about adding `.` at the end?
"May.",
"Jun.",
"Jul.",

File: src/components/molecules/Weather.tsx [hunk 2]
```diff
@@ -1,19 +1,13 @@
 import React, { useState, useEffect } from "react";
 import styles from "@/styles/components/molecules/Weather.module.scss";
-import axios from "axios";
-import { SERVER_URL } from "@/config/index";
 
 type Props = {
-  lat: number;
-  long: number;
+  data: any;
 };
```
Comment (Takashicc) [inline src/components/molecules/Weather.tsx]: Please make the `data` type to be more clear.
```ts
type WeatherData {
  location_name: string,
  temperature_c: number,
  temperature_f: number,
  humidity: number,
  weather_icon: string
}

type Props {
  data: WeatherData;
}
```

File: src/components/molecules/Weather.tsx [hunk 3]
```diff
@@ -47,40 +41,26 @@ export default function Weather(props: Props) {
...
-      .then((res) => {
-        setData(res.data);
-      });
-  }, [props.lat, props.long]);
 
-  console.log("Latitude is:", props.lat);
-  console.log("Longitude is:", props.long);
+  const WEATHER_URL = data.weather_icon
+    ? `http://openweathermap.org/img/wn/${data.weather_icon}.png`
+    : "";
```
Comment (Takashicc) [inline src/components/molecules/Weather.tsx]: I think this variable name should be `WEATHER_ICON_URL`. Because this variable is storing icon url.

File: src/components/molecules/Weather.tsx [hunk 4]
```diff
@@ -47,40 +41,26 @@ export default function Weather(props: Props) {
...
 
   return (
     <div className={styles.weather}>
-      {typeof data.main != "undefined" ? (
+      {typeof data != "undefined" ? (
```
Comment (Takashicc) [inline src/components/molecules/Weather.tsx]: Is the `data` will be `undefined`?
Because this `Weather` component is used by `Top.tsx` but It will render this component when the `data` is something.
```tsx
{data ? <Weather data={data} /> : <></>}
```

File: src/components/organisms/Top.tsx [hunk 5]
```diff
@@ -2,24 +2,32 @@ import React, { useState, useEffect } from "react";
...
 import Weather from "@/components/molecules/Weather";
 import Livedata from "./Livedata";
+import axios from "axios";
 
 export default function Top() {
-  const [lat, setLat] = useState<number | null>();
-  const [long, setLong] = useState<number | null>();
   const [currTemp, setCurrTemp] = useState<number | null>();
   const [currHumid, setCurrHumid] = useState<number | null>();
+  const [deviceId, setDeviceId] = useState<number | null>(1);
```
Comment (Takashicc) [inline src/components/organisms/Top.tsx]: Delete `1` in line 10. You are setting the `device_id` in `useEffect`.

File: src/components/organisms/Top.tsx [hunk 6]
```diff
@@ -2,24 +2,32 @@ import React, { useState, useEffect } from "react";
...
+  const [data, setData] = useState<any>([]);
```
Comment (Takashicc) [inline src/components/organisms/Top.tsx]: It is hard that what type of `data` has from the name and `any` type.
Add a specific type and change the variable name.(Like weatherData?)

File: src/components/organisms/Top.tsx [hunk 7]
```diff
@@ -2,24 +2,32 @@ import React, { useState, useEffect } from "react";
...
     setCurrHumid(68);
+    setDeviceId(1);
   }, []);
 
+  useEffect(() => {
+    axios
+      .get(`${process.env.NEXT_PUBLIC_SERVER_URL}/weather-info/en/${deviceId}`)
+      .then((res) => {
+        setData(res.data);
+      });
```
Comment (Takashicc) [inline src/components/organisms/Top.tsx]: Add a TODO comment.(Implement catch)

File: src/components/molecules/Weather.tsx [hunk 8]
```diff
@@ -27,18 +21,18 @@ export default function Weather(props: Props) {
...
       "May",
       "June",
       "July",
-      "August",
-      "September",
-      "October",
-      "November",
-      "December",
+      "Aug.",
+      "Sept.",
```
Comment (Takashicc) [inline src/components/molecules/Weather.tsx]: Change `Sept.` to `Sep.`

**Review by Takashicc — APPROVED** [review]

File: src/components/molecules/Weather.tsx [hunk 9]
```diff
@@ -27,18 +31,18 @@ export default function Weather(props: Props) {
...
-      "October",
-      "November",
-      "December",
+      "Jan.",
+      "Feb.",
+      "Mar.",
+      "Apr.",
+      "May.",
+      "June.",
+      "July.",
```
Comment (Takashicc) [inline src/components/molecules/Weather.tsx]: Change to "Jun.", "Jul.".

File: src/components/organisms/Top.tsx [hunk 10]
```diff
@@ -2,24 +2,43 @@ import React, { useState, useEffect } from "react";
...
 import Livedata from "./Livedata";
+import axios from "axios";
 
 export default function Top() {
-  const [lat, setLat] = useState<number | null>();
-  const [long, setLong] = useState<number | null>();
   const [currTemp, setCurrTemp] = useState<number | null>();
   const [currHumid, setCurrHumid] = useState<number | null>();
+  const [deviceId, setDeviceId] = useState<string | null>();
+  const [weatherData, setWeatherData] = useState<any>([]);
```
Comment (Takashicc) [inline src/components/organisms/Top.tsx]: Change the type `any`.
Use the `WeatherData`.
But define the `WeatherData` in `Top.tsx` and export. And delete the `WeatherData` in `Weather.tsx` and import from `Top.tsx`.

File: src/components/organisms/Top.tsx [hunk 11]
```diff
@@ -2,24 +2,51 @@ import React, { useState, useEffect } from "react";
...
+  weather_icon: string;
+};
 
 export default function Top() {
-  const [lat, setLat] = useState<number | null>();
-  const [long, setLong] = useState<number | null>();
   const [currTemp, setCurrTemp] = useState<number | null>();
   const [currHumid, setCurrHumid] = useState<number | null>();
+  const [deviceId, setDeviceId] = useState<string | null>();
+  const [weatherData, setWeatherData] = useState<any>([]);
```
Comment (Takashicc) [inline src/components/organisms/Top.tsx]: Change the type `any` to `WeatherData`

**Review by Takashicc — CHANGES_REQUESTED** [review]

File: src/components/organisms/Top.tsx [hunk 12]
```diff
@@ -2,24 +2,51 @@ import React, { useState, useEffect } from "react";
...
+  weather_icon: string;
+};
 
 export default function Top() {
-  const [lat, setLat] = useState<number | null>();
-  const [long, setLong] = useState<number | null>();
   const [currTemp, setCurrTemp] = useState<number | null>();
   const [currHumid, setCurrHumid] = useState<number | null>();
+  const [deviceId, setDeviceId] = useState<string | null>();
+  const [weatherData, setWeatherData] = useState<WeatherData | []>([]);
```
Comment (Takashicc) [inline src/components/organisms/Top.tsx]: Is the default value need to be `[]`? `weatherData` will be a single data not a array. Isn't `null`?

**Review by Takashicc — CHANGES_REQUESTED** [review]

**Review by Takashicc — APPROVED** [review]
LGTM!!
